### ISSUE TITLE
Language only Chinese

### ISSUE THREAD

**Issue by SallyBones** [ZhuRuoLing/startup-time#1]
Hello, Nice mod, small problem for me though, the language is only in Chinese and i cant understand the time taken. Can the language be set to the same one used in game? If not thats fine ill learn chinese overnight no problem.

**Comment by ZhuRuoLing** [comment]
A i18n-supported version compatible with minecraft 1.19.2-1.20.1 has been uploaded to [modrinth](https://modrinth.com/mod/startup-time/version/H6iKh0Hk)
and there is also a i18n-supported version compatible with 1.20.4 [here](https://modrinth.com/mod/startup-time/version/1.1.0)
