### ISSUE TITLE
启动崩溃，但是站内的非官方版能正常启动游戏

### ISSUE THREAD

**Issue by QianYI-Yan** [ZhuRuoLing/startup-time#5]
https://www.mcmod.cn/class/15961.html
两者是有啥差别吗（我认为再排一遍mod会死
[2024-09-17-1.log](https://github.com/user-attachments/files/17023143/2024-09-17-1.log)

**Comment by ZhuRuoLing** [comment]
好问题....我找不到我1.21版本的mod源码了
重新做一遍好了

**Comment by ZhuRuoLing** [comment]
重新做了一下
在 [这里](https://modrinth.com/mod/startup-time/version/1.1.2) 下载最新的支持1.21的版本

**Comment by QianYI-Yan** [comment]
> 重新做了一下 在 [这里](https://modrinth.com/mod/startup-time/version/1.1.2) 下载最新的支持1.21的版本

我爱你
